// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace EmployeeWebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyName = "Turkcell",
                            WebSite = "www.turkcell.com"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyName = "Samsun Üniversitesi",
                            WebSite = "www.samsun.edu.tr"
                        },
                        new
                        {
                            CompanyId = 3,
                            CompanyName = "Aselsan",
                            WebSite = "www.aselsan.com"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            FirstName = "Ahmet",
                            LastName = "Ağ",
                            Salary = 30000m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            FirstName = "Mehmet",
                            LastName = "Güneş",
                            Salary = 35000m
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            FirstName = "Filiz",
                            LastName = "Irmak",
                            Salary = 39000m
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            FirstName = "Hatice",
                            LastName = "Bulut",
                            Salary = 40000m
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            FirstName = "Can",
                            LastName = "Deniz",
                            Salary = 45000m
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
