// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace ProductApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231225115001_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AtCreatedDate = new DateTime(2023, 12, 25, 11, 50, 1, 16, DateTimeKind.Utc).AddTicks(1976),
                            ProductId = 1,
                            Text = "Harika bir ürün."
                        },
                        new
                        {
                            CommentId = 2,
                            AtCreatedDate = new DateTime(2023, 12, 25, 11, 50, 1, 16, DateTimeKind.Utc).AddTicks(1979),
                            ProductId = 1,
                            Text = "Berbat bir ürün."
                        },
                        new
                        {
                            CommentId = 3,
                            AtCreatedDate = new DateTime(2023, 12, 25, 11, 50, 1, 16, DateTimeKind.Utc).AddTicks(1980),
                            ProductId = 1,
                            Text = "Hızlı kargo, güvenilir satıcı."
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 27000m,
                            ProductName = "HP Laptop"
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 7000m,
                            ProductName = "Kulaklık"
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 1000m,
                            ProductName = "Keyboard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
