// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demo1.Repository;

#nullable disable

namespace demo1.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("demo1.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Country = "USA",
                            Name = "Apple"
                        },
                        new
                        {
                            CompanyId = 2,
                            Country = "USA",
                            Name = "Samsung"
                        },
                        new
                        {
                            CompanyId = 3,
                            Country = "China",
                            Name = "Huawei"
                        });
                });

            modelBuilder.Entity("demo1.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            CompanyId = 1,
                            Model = "iPhone 14 Pro",
                            Price = 1000m,
                            Size = 10.199999999999999
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            CompanyId = 2,
                            Model = "S20",
                            Price = 1200m,
                            Size = 9.0
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            CompanyId = 3,
                            Model = "F60",
                            Price = 900m,
                            Size = 7.0
                        });
                });

            modelBuilder.Entity("demo1.Models.Phone", b =>
                {
                    b.HasOne("demo1.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
