@startuml SpaceShip
abstract class SpaceShip{
    + Name: string
    + Mass: double
    + Fuel: double
    + CrewCapacity: int
    + Thrust: double
    + SpecificImpulse: double
    + SpaceShip(Name: string, Mass: double, Fuel: double, CrewCapacity: int, Thrust: double, SpecificImpulse: double)
    + {abstract} Launch(): void
    + {abstract} Land(): void
    + TravelTo(planet: Planet): void
    # CalculateDeltaV(Gravity: double): double
    # CalculateTravelDistance(deltaV: double): double
}
@enduml